
import van from "vanjs-core"

const { body, button, div, form, h1, h2, h3, h4, head, header, html, input, label, link, meta, option, p, path, script, section, select, small, span, svg, textarea, title, ul, li, ol, br,a } = van.tags
export {
    body,
    button,
    div,
    form,
    h1,
    h2,
    h3,
    h4,
    head,
    header,
    html,
    input,
    label,
    link,
    meta,
    option,
    p,
    path,
    script,
    section,
    select,
    small,
    span,
    svg,
    textarea,
    title,
    ul,
    li,
    ol,
    br,
    a,
};